language: objective-c

script:
- xctool -workspace BLCStarRatingView.xcworkspace -scheme BLCStarRatingViewTests -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO test -test-sdk iphonesimulator7.1 -simulator ipad
